export default function getStyles(t, leftCollapsed, rightCollapsed, leftWidth, rightWidth, isDragging) {
  return {
    tabBarContainer: {
      display: 'flex',
      flexDirection: 'column', 
      gap: '10px',
      flex: 1
    },
    app: { display: 'flex', flexDirection: 'column', width: '100vw', height: '100vh', fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif', fontSize: '14px', color: t.text, backgroundColor: t.bg, userSelect: isDragging ? 'none' : 'auto' },
    header: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', height: '52px', padding: '0 20px', backgroundColor: t.bgSecondary, flexShrink: 0 },
    headerTitle: { fontSize: '14px', fontWeight: 600, color: t.textHeading, letterSpacing: '-0.2px' },
    headerActions: { display: 'flex', alignItems: 'center', gap: '8px' },
    badge: { fontSize: '12px', padding: '3px 9px', background: t.bgTertiary, borderRadius: '5px', color: t.textSecondary, fontWeight: 500 },
    iconBtn: { padding: '10px 10px', background: "linear-gradient(90deg, #6e01dc, #23dcdc)", border: 'none', borderRadius: '50%', fontSize: '12px', cursor: 'pointer', color: '#fff' },
    main: { display: 'flex', flex: 1, overflow: 'hidden', padding: '8px', gap: '0' },
    leftPanel: { width: leftCollapsed ? '60px' : `${leftWidth}px`, minWidth: leftCollapsed ? '44px' : `${leftWidth}px`, backgroundColor: t.bgSecondary, border: 'none', borderRadius: '8px', display: 'flex', flexDirection: 'column', overflow: 'hidden', flexShrink: 0, transition: isDragging ? 'none' : 'width 0.15s ease, min-width 0.15s ease' },
    rightPanel: { width: rightCollapsed ? '60px' : `${rightWidth}px`, minWidth: rightCollapsed ? '44px' : `${rightWidth}px`, backgroundColor: t.bgSecondary, border: 'none', borderRadius: '8px', display: 'flex', flexDirection: 'column', overflow: 'hidden', flexShrink: 0, transition: isDragging ? 'none' : 'width 0.15s ease, min-width 0.15s ease' },
    canvas: { flex: 1, borderRadius: '8px', border: 'none', overflow: 'hidden', margin: '0 4px' },
    panelHeader: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '12px 14px', backgroundColor: t.bgSecondary, flexShrink: 0, minHeight: '48px' },
    sectionTitle: { fontSize: '16px', fontWeight: 700, color: t.textHeading, textTransform: 'none', letterSpacing: '-0.3px', WebkitFontSmoothing: "antialiased", MozOsxFontSmoothing: "grayscale", fontFamily:'monospace' },
    panelSection: { padding: '14px' },
    divider: { height: '0px', backgroundColor: 'transparent' },
    form: { display: 'flex', flexDirection: 'column', gap: '12px' },
    formGroup: { display: 'flex', flexDirection: 'column', gap: '5px' },
    label: { fontSize: '12px', fontWeight: 500, color: t.textSecondary },

    input: {
      padding: '8px 10px',
      borderRadius: '6px',
      fontSize: '13px',
      outline: 'none',
      fontFamily: 'monospace',
      boxSizing: 'border-box',
      backgroundColor: t.bgSecondary === '#050505' ? '#111111' : '#ffffff',
      color: t.bgSecondary === '#050505' ? '#ffffff' : '#1f2937',
      border: `1px solid ${t.bgSecondary === '#050505' ? '#222222' : '#cbd5e1'}`,
    },

    primaryBtn: { padding: '9px 14px', background: t.primary, color: '#fff', border: 'none', borderRadius: '6px', fontSize: '13px', fontWeight: 500, cursor: 'pointer', marginTop: '4px' },
    smallBtn: { padding: '6px 10px', background: t.bgTertiary, border: 'none', borderRadius: '6px', fontSize: '12px', cursor: 'pointer', color: t.text },
    tabBtnActive: { padding: '6px 12px', background: t.bgTertiary, borderRadius: '6px', fontSize: '12px', cursor: 'pointer', color: t.textHeading, fontWeight: 600, border: 'none' },
    tabBtnInactive: { padding: '6px 12px', background: 'transparent', border: '1px solid transparent', borderRadius: '6px', fontSize: '12px', cursor: 'pointer', color: t.textSecondary },
    dangerBtn: { padding: '7px 12px', background: t.danger, border: 'none', borderRadius: '6px', fontSize: '12px', fontWeight: 500, cursor: 'pointer', color: '#fff' },
    infoRow: { display: 'flex', justifyContent: 'space-between', fontSize: '12px', gap: '8px', padding: '4px 0' },
    infoLabel: { color: t.textSecondary },
    infoValue: { color: t.textHeading, fontFamily: 'monospace' },
    emptyState: { padding: '24px 16px', textAlign: 'center', fontSize: '12px', color: t.textMuted, background: t.bgTertiary, borderRadius: '6px', border: `1px dashed #222222`, lineHeight: '1.4' },
    codeBlock: {
      flex: 1,
      margin: 0,
      padding: '14px 16px',
      overflow: 'auto',
      fontFamily: '"SF Mono", Menlo, Monaco, monospace',
      fontSize: '12px', lineHeight: '1.6',
      color: t.text,
      background: t.codeBg,
      whiteSpace: 'pre',
      height: '100%',
      boxSizing: 'border-box',
      scrollbarWidth: 'thin',
      scrollbarColor: t.bgSecondary === '#050505' ? '#333333 #050505' : '#cbd5e1 #f3f4f6'
    },

    codeEditorInput: {
      flex: 1,
      minHeight: '160px',
      width: '100%',
      boxSizing: 'border-box',
      fontFamily: '"SF Mono", Menlo, Monaco, monospace',
      fontSize: '12px',
      lineHeight: '1.5',
      padding: '12px',
      background: t.codeBg,
      color: t.text,
      border: `1px solid ${t.borderStrong}`,
      borderRadius: '6px',
      outline: 'none',
      resize: 'none',
      whiteSpace: 'pre',
      overflowX: 'auto',
      scrollbarWidth: 'thin',
      scrollbarColor: t.bgSecondary === '#050505' ? '#333333 #000000' : '#cbd5e1 #f8fafc'
    }
  };
}